name: bin_shield_app
description: "Um novo projeto Flutter."

# A linha abaixo impede que o pacote seja acidentalmente publicado no pub.dev
# usando `flutter pub publish`. Isso é preferível para pacotes privados.
publish_to: 'none'  # Remova esta linha se desejar publicar no pub.dev

# Define a versão e o número de compilação para sua aplicação.
# O número da versão é composto por três números separados por pontos, como 1.2.43
# seguido por um número de compilação opcional separado por +.
# Tanto a versão quanto o número de compilação podem ser sobrescritos durante
# a compilação do Flutter, especificando --build-name e --build-number, respectivamente.
# No Android, build-name é usado como versionName enquanto build-number é usado como versionCode.
# Saiba mais sobre versionamento no Android em https://developer.android.com/studio/publish/versioning
# No iOS, build-name é usado como CFBundleShortVersionString enquanto build-number é usado como CFBundleVersion.
# Saiba mais sobre versionamento no iOS em
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# No Windows, build-name é usado nas partes principais, menores e de correção
# da versão do produto e do arquivo, enquanto build-number é usado como o sufixo de compilação.
version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <4.0.0'

# As dependências especificam outros pacotes que seu pacote precisa para funcionar.
# Para atualizar automaticamente suas dependências para as versões mais recentes,
# considere executar `flutter pub upgrade --major-versions`. Alternativamente,
# as dependências podem ser atualizadas manualmente alterando os números das versões abaixo para
# as versões mais recentes disponíveis no pub.dev. Para ver quais dependências têm versões mais novas,
# execute `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.10.0
  firebase_auth: ^5.4.0
  cloud_firestore: ^5.6.1
  geolocator: ^13.0.2
  google_sign_in: ^6.2.2
  table_calendar: ^3.0.8
  font_awesome_flutter: ^10.8.0
  googleapis: ^9.0.0
  square_in_app_payments: ^1.7.10
  in_app_purchase: ^3.2.1
  flutter_stripe: ^11.4.0
  pay: ^3.1.0
  flutter_dotenv: ^5.2.1
  cupertino_icons: ^1.0.8
  


  # O pacote abaixo adiciona a fonte de ícones Cupertino à sua aplicação.
  # Use com a classe CupertinoIcons para ícones no estilo iOS.


dev_dependencies:
  flutter_test:
    sdk: flutter

  # O pacote "flutter_lints" abaixo contém um conjunto de lints recomendados para
  # incentivar boas práticas de codificação. O conjunto de lints fornecido pelo pacote é
  # ativado no arquivo `analysis_options.yaml` localizado na raiz do seu pacote.
  # Consulte esse arquivo para obter informações sobre como desativar lints específicos
  # e ativar outros.
  flutter_lints: ^4.0.0

# Para mais informações sobre a parte genérica do Dart deste arquivo, consulte a
# seguinte página: https://dart.dev/tools/pub/pubspec

# A seção abaixo é específica para pacotes Flutter.
flutter:

  # A linha abaixo garante que a fonte de ícones Material seja incluída
  # em sua aplicação, para que você possa usar os ícones da classe Material Icons.
  uses-material-design: true

  # Para adicionar assets à sua aplicação, adicione uma seção assets, como esta:
  assets:
    - assets/logo.png
    - assets/google.png
    - assets/cadastro.png
    - assets/google_pay_config.json
    - assets/apple_pay_config.json

  #   - images/a_dot_ham.jpeg

  # Um asset de imagem pode se referir a um ou mais "variantes" específicas de resolução.
  # Consulte https://flutter.dev/to/resolution-aware-images

  # Para mais detalhes sobre como adicionar assets de dependências de pacotes, consulte
  # https://flutter.dev/to/asset-from-package

  # Para adicionar fontes personalizadas à sua aplicação, adicione uma seção fonts aqui,
  # nesta seção "flutter". Cada entrada desta lista deve ter uma chave "family" com o nome
  # da família da fonte e uma chave "fonts" com uma lista fornecendo o asset e outros descritores
  # para a fonte. Por exemplo:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf  
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # Para mais detalhes sobre fontes de dependências de pacotes, consulte
  # https://flutter.dev/to/font-from-package
