// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwOd08z7W0FpCmaMmKAn5AjJIDfJDA6YE',
    appId: '1:771775333882:web:a5b3418a06fc74cb091043',
    messagingSenderId: '771775333882',
    projectId: 'binshieldapp',
    authDomain: 'binshieldapp.firebaseapp.com',
    storageBucket: 'binshieldapp.firebasestorage.app',
    measurementId: 'G-NVMYMQ4LXM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB64QWdz1nF6xolGbxMLn6DdZu1dSdBf90',
    appId: '1:771775333882:android:8dfde4a8b633b8f4091043',
    messagingSenderId: '771775333882',
    projectId: 'binshieldapp',
    storageBucket: 'binshieldapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAv5K31avzNe9vXnLIDSZ7XTOfQtACnzsM',
    appId: '1:771775333882:ios:998aeeecc8efc293091043',
    messagingSenderId: '771775333882',
    projectId: 'binshieldapp',
    storageBucket: 'binshieldapp.firebasestorage.app',
    iosClientId: '771775333882-snt22k8e373gtd1eublo0s4smkrc1vi7.apps.googleusercontent.com',
    iosBundleId: 'com.example.binShieldApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAv5K31avzNe9vXnLIDSZ7XTOfQtACnzsM',
    appId: '1:771775333882:ios:998aeeecc8efc293091043',
    messagingSenderId: '771775333882',
    projectId: 'binshieldapp',
    storageBucket: 'binshieldapp.firebasestorage.app',
    iosClientId: '771775333882-snt22k8e373gtd1eublo0s4smkrc1vi7.apps.googleusercontent.com',
    iosBundleId: 'com.example.binShieldApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBwOd08z7W0FpCmaMmKAn5AjJIDfJDA6YE',
    appId: '1:771775333882:web:8d1adca3a17d8c8d091043',
    messagingSenderId: '771775333882',
    projectId: 'binshieldapp',
    authDomain: 'binshieldapp.firebaseapp.com',
    storageBucket: 'binshieldapp.firebasestorage.app',
    measurementId: 'G-87V2KEL1KX',
  );

}